deeppavlov/dream

.github/workflows/black_codestyle.yml, .github/workflows/flake8_codestyle.yml, annotators/COMeT/comet_commonsense/interface.py, annotators/COMeT/comet_commonsense/schemas.py, annotators/COMeT/comet_commonsense/src/data/atomic.py, annotators/COMeT/comet_commonsense/src/data/conceptnet.py, annotators/COMeT/comet_commonsense/src/data/data.py, annotators/COMeT/comet_commonsense/src/data/utils.py, annotators/COMeT/comet_commonsense/src/evaluate/sampler.py, annotators/COMeT/comet_commonsense/src/interactive/functions.py, annotators/COMeT/comet_commonsense/src/models/gpt.py, annotators/COMeT/comet_commonsense/src/models/models.py, annotators/COMeT/comet_commonsense/src/models/utils.py, annotators/COMeT/comet_commonsense/utils/utils.py, annotators/COMeT/server.py
it changes trigger for github action of code style, upd style
=> fix style & upd condition of black

annotators/combined_classification/server.py, state_formatters/dp_formatters.py
- made a crucial fix in formatter
- added logging of the exec time
=> Fixes of combined classifier

annotators/news_api/newsapi_service.py, annotators/news_api/server.py, pipeline_conf.json
our current news api plan. so, changing maximum articules to 20, increasing timeout
=> fix: news api num news and renew freqs

dockerfile_agent
=> Release v0.1.3

annotators/wiki_parser/README.md, annotators/wiki_parser/wiki_parser.py
Add function in wiki_parser to define relation between two entities.
=> relation between two entities

assistant_dists/deepy_adv/pipeline_conf.json, assistant_dists/deepy_base/pipeline_conf.json, assistant_dists/deepy_faq/pipeline_conf.json, assistant_dists/deepy_gobot_base/pipeline_conf.json, assistant_dists/dream/pipeline_conf.json, assistant_dists/dream_mini/pipeline_conf.json, assistant_dists/dream_mini_persona_based/pipeline_conf.json, assistant_dists/dream_multilingual/pipeline_conf.json, assistant_dists/dream_multimodal/pipeline_conf.json, assistant_dists/dream_russian/pipeline_conf.json, assistant_dists/dream_sfc/pipeline_conf.json, components.json
=> Add metadata to pipeline configs

skills/dff_book_skill/tests/concrete_book_out.json, skills/dff_book_skill/tests/favs_in.json, skills/dff_book_skill/tests/favs_out.json
Book skill fix - updated "years ago" in tests
=> Book skill fix - updated "years ago" in tests

annotators/entity_detection/Dockerfile, annotators/entity_detection/requirements.txt, annotators/kbqa/requirements.txt, annotators/wiki_parser/test_wiki_parser.py, skills/factoid_qa/requirements.txt
=> Release v0.9.1

annotators/user_knowledge_graph/Dockerfile, annotators/user_knowledge_graph/server.py
This replaces the manual creation of abstract kinds with an automatic process provided by deeppavlov-kg. Also, relationships now automatically get fully-qualified names.
=> fix: create User kind if doesn't exist

.env, assistant_dists/dream_multimodal/dev.yml, assistant_dists/dream_multimodal/docker-compose.override.yml, assistant_dists/dream_multimodal/pipeline_conf.json, docker-compose.yml, dockerfile_agent, services/image_captioning/server.py, skill_selectors/rule_based_selector/connector.py, skills/dff_image_skill/Dockerfile, skills/dff_image_skill/README.md, skills/dff_image_skill/requirements.txt, skills/dff_image_skill/scenario/condition.py, skills/dff_image_skill/scenario/main.py, skills/dff_image_skill/scenario/processing.py, skills/dff_image_skill/scenario/response.py, skills/dff_image_skill/server.py, skills/dff_image_skill/test.sh, skills/dff_image_skill/test_server.py, skills/dff_image_skill/tests/lets_talk_in.json, skills/dff_image_skill/tests/lets_talk_out.json, state_formatters/dp_formatters.py
=> Release v0.13.0

assistant_dists/deepy_adv/docker-compose.override.yml, assistant_dists/deepy_base/docker-compose.override.yml, assistant_dists/deepy_faq/docker-compose.override.yml, assistant_dists/deepy_gobot_base/docker-compose.override.yml, assistant_dists/dream/dev.yml, assistant_dists/dream/docker-compose.override.yml, assistant_dists/dream_mini/dev.yml, assistant_dists/dream_mini/docker-compose.override.yml, assistant_dists/dream_mini_persona_based/dev.yml, assistant_dists/dream_mini_persona_based/docker-compose.override.yml, assistant_dists/dream_multimodal/dev.yml, assistant_dists/dream_multimodal/docker-compose.override.yml, assistant_dists/dream_sfc/dev.yml, assistant_dists/dream_sfc/docker-compose.override.yml
- fix: revert to simple spellcheck (#295)
=> Release v0.13.1

annotators/toxic_classification_ru/requirements.txt, annotators/toxic_classification_ru/server.py, assistant_dists/dream_russian/dev.yml, assistant_dists/dream_russian/docker-compose.override.yml
Does not work https://huggingface.co/s-nlp/russian_toxicity_classifier
=> fix: russian_toxic

annotators/combined_classification/requirements.txt
=> Updated torch version for combined classification to work with compute capability 80

skills/dff_book_skill/tools/wiki.py
=> Book skill fix

assistant_dists/deepy_assistant/docker-compose.override.yml
- fix: secrets for deepy assistant
=> Release v0.17.3

assistant_dists/fairytale_assistant/docker-compose.override.yml, assistant_dists/fairytale_assistant/pipeline_conf.json, skills/dff_template_prompted_skill/component.yml, skills/dff_template_prompted_skill/pipeline.yml
sometime has to generate looong stuff (fairytales themselves), leading to timeout
=> timeout 30 for fairytales

common/dff_api_v1/requirements.txt, skills/dff_template_skill/tests/lets_talk_out.json
fix pydantic version under 2.0
=> fix pydantic under 2.0

annotators/doc_retriever/README.md, annotators/prompt_selector/service_configs/dream_persona_openai_prompted/environment.yml, annotators/prompt_selector/service_configs/dream_persona_openai_prompted/service.yml, assistant_dists/document_based_qa/pipeline_conf.json, assistant_dists/dream_persona_openai_prompted/dev.yml, assistant_dists/dream_persona_openai_prompted/docker-compose.override.yml, assistant_dists/dream_persona_openai_prompted/pipeline_conf.json, response_selectors/llm_based_response_selector/server.py, skill_selectors/description_based_skill_selector/connector.py, skills/dff_document_qa_llm_skill/README.md
feat: use dream_faq in dream_openai_persona_prompted
=> Release v1.8.2

annotators/combined_classification_lightweight/Dockerfile
кажется, перепутаны названия аннотаторов. по крайней мере сейчас lightweight просто не поднимается
=> fix: combined lightweight folder

skills/dff_template_prompted_skill/service_configs/dff-dream-faq-prompted-skill/environment.yml
PR covers task from Jira:
https://deeppavlov.atlassian.net/browse/DREAM-1704
=> fixing path to chatgpt skill configurations

common/generative_configs/openai-text-davinci-003.json
=> Modify davinci config so it works better in russian

annotators/property_extraction/rel_ranking_roberta.json, annotators/property_extraction/server.py, annotators/property_extraction/test_property_extraction.py
Property extraction can now extract cities/countries as subjects. Minor fixes.
=> update property extraction

skills/dff_universal_prompted_skill/scenario/response.py
=> Add configs to envvars_to_send

assistant_dists/dream_kg/pipeline_conf.json, assistant_dists/dream_kg_prompted/dev.yml, assistant_dists/dream_kg_prompted/docker-compose.override.yml, assistant_dists/dream_kg_prompted/pipeline_conf.json, components/wM5Hf4GVelUr2s8vrTBtaS.yml
Fixed port for property-extraction in dream_kg_prompted distribution
=> Dream kg prompted port fix
